name: go-bloom

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  GO_VERSION: '1.22'
  GOLANGCI_LINT_VERSION: v1.59

jobs:
  lint-and-test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version:  ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Unit Test
        run: go test -v ./...
